#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  snaps:
    - name: quassel-kalikiana
  refresh-installer:
    update: true
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: codetihng-ThinkPad-P14s-Gen-4
    password: $6$I0kFjwOPMwii7L90$oxlvexAKJ.gAx8KDE2Zb/tZqaQ.h5mESkJCZhkFeQ7DN9nsVUMvNhVNG9mslGUHVx0E8HA3LXfNFmLeHcqG3T.
    realname: codetihng
    username: codetihng
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: gb
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      enx0050b6ab3f62:
        dhcp4: true
    version: 2
    wifis: {}
  oem:
    install: auto
  source:
    id: ubuntu-desktop
    search_drivers: true
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: false
  storage:
    layout:
      name: lvm
      password: insecure
      sizing-policy: all
  timezone: Europe/London
  updates: security
  shutdown: poweroff
  version: 1
